sudo: required
services:
    - docker

before_install:
    - docker build -t sharidas/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run sharidas/react-test npm test -- --coverage

after_success:
    - docker build -t sharidasan/multi-client ./client
    - docker build -t sharidasan/multi-nginx ./nginx
    - docker build -t sharidasan/multi-server ./server
    - docker build -t sharidasan/multi-worker ./worker
    # Login to docker cli
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # take these images and push them to docker hub
    - docker push sharidasan/multi-client
    - docker push sharidasan/multi-nginx
    - docker push sharidasan/multi-server
    - docker push sharidasan/multi-worker

deploy:
    edge: true
    provider: elasticbeanstalk
    region: ap-south-1
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-ap-south-1-367913748319
    bucket_path: docker-multi
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
